config/routes.rb
WeltDerUnikate::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  constraints subdomain: 'administration' do
    namespace(:admin, path: '/') do
      get '/' => :show
      get :maillog
      resources :art_associations, except: [:destroy, :show]
      resources :members do
        get :update_monthly_charge_for_all_users
        member do
          get :purchases_and_sales
          get :user_profile
          get :user_settings
          get "shop_profile/about_me"           => :shop_profile_about_me
          get "shop_profile/settings"           => :shop_profile_settings
          get "shop_profile/terms_and_imprint"  => :shop_profile_terms_and_imprint
          get "shop_profile/revocation"         => :shop_profile_revocation
          post :update_user_data
          get :update_monthly_charge_for_the_user
          get :restore_deleted_account
        end
      end
      resources :invoices, only: [] do
        collection do
          get :created
          get :open
          get :paid
          get :cancellations
          get :credits
          get :check_boxes_action
          get :send_monthly_invoice
          get :send_commission_invoice
        end
      end
      resources :correspondence, only: [:index] do
        collection do
          get :registration
          get :new_shop
          get :to_old_email_about_email_changing
          get :confirmation_email
          get :password_changed
          get :articles_order_dispatched
          get :article_is_already_sold
          get :new_order_message_from_buyer
          get :new_order_message_from_seller
          get :buyer_cancellation
          get :seller_cancellation
          get :new_message
          get :purchase_notification_confirmed_to_buyer
          get :purchase_notification_confirmed_to_seller
          get :purchase_notification_unconfirmed_to_buyer
          get :purchase_notification_unconfirmed_to_seller
          get :share_article
          get :new_voucher
        end
      end
      resources :newsletters, only: [:new, :create]
      resources :business_cards, only: [:index] do
        post :change_details, on: :member
      end
      resources :vouchers, only: :index do
        get :change, on: :collection
        member do
          post :change_status
          post :change_paid_on
        end
      end
      get :text_content
      scope :text_content do
        resources :faq_sections,
            param: :faq_section_id do
          member do
            resources :faq_questions,
                param: :faq_question_id,
                except: :index
          end
        end
        get :discover_the
        get :find_yours
      end
    end
  end

  get 'admin', to: redirect(subdomain: 'administration', path: '/')
  get 'admin/:any', to: redirect(subdomain: 'administration', path: '/%{any}')

  constraints subdomain: false do
    resources :invoices, only: [:index, :show]
  end
  resources :invoices, only: [] do
    get :pdf_version, on: :member
  end

  resources :favorites, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :articles_view_types, only: [] do
    get :change, on: :collection
  end

  resources :messages, except: [:index] do
    member do
      get :reply
      get :to_trash
    end
    collection do
      get  :inbox
      get  :sent
      get  :drafts
      get  :bin
      get  :archive
      post :check_boxes_action
      get  :empty_trash
    end
  end

  resources :orders do
    collection do
      get :open
      get :completed
      get :canceled
    end
  end

  resources :purchases do
    member do 
      get  :addresses_and_payment_types
      get  :check_order
      get  :complete
    end
    collection do
      get :open
      get :completed
    end
  end

  resources :articles, except: :index do
    post :change, on: :member
    collection do
      get :sold
      get :deleted
      get :delete_all
      get :online
      get :offline
      get :templates
    end
  end


  resources :documents

  scope :search do
    get '/:search', to: 'articles#search'
    get '/', to: 'articles#search'
  end

  resources :payment_infos
  resources :payment_selections
  resources :shipping_methods
  resources :pictures, only: [:create, :destroy, :edit] do
    post :crop, on: :member
    post :create_shop_main, on: :collection
  end

  resources :withdrawal_forms, only: [:create, :destroy] do
    get :preview, on: :member
  end

  resources :shopping_baskets, only: [:create,
                                      :index,
                                      :update,
                                      :destroy]

  resources :articles_orders, only: [:destroy] do
    member do
      get :paypal_payment
      get :bank_details
      get :credit_card_payment
      post :credit_card_payment
      get :write_a_review
      get :write_a_review_for_buyer
      get :mark_as_sold
      get :mark_order_messages_as_read
      patch :use_voucher
      patch :set_payment_type
      patch :set_pickup_as_shipping_method
      patch :use_shipping_address
      get :closure_confirmation
      get :close
      get :cancel
      patch :update_status
      get :send_payment_reminder
    end
  end

  resources :credit_card_data, only: [:create]

  get '/' => 'shops#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www"}

  controller :pages do
    root to: :home
    get :imprint
    get :privacy
    get :about_jakira
    get :terms
  end

  resources :categories, only: :show

  devise_for :users, controllers: {registrations: 'users/registrations',
                                   sessions: 'users/sessions',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations',
                                   omniauth_callbacks: "users/omniauth_callbacks"}
  # devise_scope :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end

  resources :ratings, only: [:update, :index]

  resources :shops, except: [:edit, :index] do
    collection do
      get :about_me
      get :settings
      get :terms_and_imprint
      get :revocation
      get :open
    end
    member do
      get :show_terms
      get :show_revocation
      get :ratings
      get :download_withdrawal_form
    end
  end

  resources :order_messages, only: [:create, :show]
  resources :share, only: [:new, :create, :index]

  resources :business_cards, only: [:index, :create]

  resources :vouchers, only: [:show, :new, :create] do
    get :after_payment, on: :collection
    get :pdf_version, on: :member
  end

  resources :main_voucher_data, only: :update

  resources :addresses, only: [] do
    get :load_country_code, on: :collection
    member do
      post :update_purchase_address
    end
  end

  resources :art_associations,
      only: [:create, :index] do
    collection do
      get :register
      patch :become_a_member
      scope :admin_panel, as: 'admin_panel' do
        get :events
        get :settings
        scope as: 'art_associations' do
          resources :members,
              controller: 'art_associations/members',
              except: [:show, :destroy] do
            post :import_xls, on: :collection
          end
        end
      end
    end
  end

  resources :faq, only: [:index, :show]

  get '/contact', to: 'contacts#new'
  resources :contacts, only: [:create]
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [ :update,
                                   :show,
                                   :destroy,
                                   :ratings,
                                   :download_withdrawal_form]

  before_action :set_current_user_shop, only: [ :about_me,
                                                :settings,
                                                :terms_and_imprint,
                                                :revocation]

  before_action :check_if_shop_is_deleted,
                  except: [:new,
                           :create,
                           :update,
                           :download_withdrawal_form,
                           :open]


  before_action :authenticate_user!,
                  only: [:new, :create, :destroy, :update, :open]

  skip_authorization_check

  def ratings
    @user = @shop.user
    @address = @shop.address
    @reviews = @user.received_ratings.finished
    if params[:rating].present?
      @reviews = @reviews.where(score: params[:rating])
    end
    if params[:displays].present? && params[:displays] != "all"
      @reviews = @reviews.where(from: params[:displays])
    else
      @reviews
    end
  end

  def show
    @user = @shop.user
    if @shop.online == true || current_user == @user
      @articles = @shop.articles.visible.page(params[:page]).per(24)
      @address = @shop.address
    else
      redirect_to :root, notice: t(".the_shop_is_not_available.")
    end
  end

  def new
    if current_or_guest_user.art_association.present?
      redirect_to :root, alert: t(".your_shop_is_already_present") if current_user.has_shop?
      if current_or_guest_user.shop.present?
        @shop = current_or_guest_user.shop
      else
        @shop = Shop.new
        @shop.build_address(current_user.address.attributes.except("id"))
        @shop.build_bank_transfer_data
        @shop.build_personal_bank_data
        @shop.build_paypal_data
        @shop.build_shipping_readiness
      end
      ["pickup",
       "free_within_germany",
       "within_germany",
       "within_eu",
       "worldwide"].each do |shipping_method_name|
        @shop.shipping_methods.build(name: shipping_method_name) if !@shop.shipping_methods.map(&:name).include?(shipping_method_name)
      end
    else
      flash.notice = t 'access_denied'
      redirect_to_back_or_default
    end
  end

  def about_me
    @main_picture = MainPicture.new
  end

  def download_withdrawal_form
    send_file @shop.withdrawal_form.file.path
  end

  def settings
    current_user.shop.build_bank_transfer_data if current_user.shop.bank_transfer_data.nil?
    current_user.shop.build_paypal_data        if current_user.shop.paypal_data.nil?
    ["pickup",
     "free_within_germany",
     "within_germany",
     "within_eu",
     "worldwide"].each do |shipping_method_name|
      if !current_user.shop.shipping_methods.map(&:name).include?(shipping_method_name)
        current_user.shop.shipping_methods.build(name: shipping_method_name)
      end
    end
  end

  def terms_and_imprint
  end

  def revocation
  end

  def open
    @user = current_or_guest_user
    redirect_to new_shop_url if @user.art_association.present?
  end

  def create
    @shop =
      current_user.build_shop(shop_params
                  .merge(picture_ids: params[:picture_ids]))
    @shop.address.first_name = current_user.address.first_name
    @shop.address.last_name = current_user.address.last_name
    if @shop.save
      UserMailer.new_shop(@shop.user).deliver
      redirect_to root_url(subdomain: @shop.subdomain),
                           notice: t('.successfull_created')
    else
      render 'new'
    end
  end

  def update
    @user = @shop.user
    if params[:update_shop_images] || params[:create_shop]
      @shop.picture_ids = params[:picture_ids]
    end
    if params[:delete_main_image] == "true"
      @shop.remove_image!
    end
    @shop.slug = nil
    if @shop.update(shop_params)
      if @shop.withdrawal_form.present? &&
          (params[:shop].present? &&
            !params[:shop][:withdrawal_form_id].present?)
        @shop.withdrawal_form.destroy
      end
      @shop.update(deleted: false)
      flash.notice = t('.successfull_updated')
      if params[:settings]
        if !current_user.admin?
          redirect_to settings_shops_url
        else
          redirect_to shop_profile_settings_admin_member_url(id: @user.membership_number)
        end
      elsif params[:create_shop]
        UserMailer.new_shop(@shop.user).deliver
        redirect_to root_url(subdomain: @shop.subdomain)
      else
        redirect_to :back
      end
    else
      ["pickup",
       "free_within_germany",
       "within_germany",
       "within_eu",
       "worldwide"].each do |shipping_method_name|
        if !@shop.shipping_methods.map(&:name).include?(shipping_method_name)
          @shop.shipping_methods.build(name: shipping_method_name)
        end
      end
      if params[:create_shop]
        render action: 'new'
      elsif !current_user.admin?
        render action: 'settings'
      else
        render "admin/members/shop_profile_settings"
      end
    end
  end

  def destroy
    @shop.articles.each do |article|
      article.update(status: "offline")
    end
    UserMailer.seller_cancellation(@shop.user).deliver
    @shop.update(deleted: true)
    redirect_to :edit_user_registration
  end

  private

  def set_shop
    @shop = Shop.find_by(slug: params[:id]) || Shop.find_by(subdomain: request.subdomain)
  end

  def set_current_user_shop
    @shop = current_or_guest_user.shop
  end

  def check_if_shop_is_deleted
    if @shop.nil? || @shop.deleted?
      flash.alert = t ".the_shop_does_not_exist"
      redirect_to_back_or_default
    end
  end

  def shop_params
    params.require(:shop).permit(:_destroy,
                                 :payment_authorization,
                                 :id,
                                 :address_id,
                                 :online,
                                 :order_confirmation,
                                 :revocation,
                                 :articles_type,
                                 :revocation_physical_products,
                                 :revocation_services,
                                 :revocation_digital_content,
                                 :name,
                                 :subdomain,
                                 :company_type,
                                 :corporate_form,
                                 :tax_number,
                                 :field_of_action,
                                 :default_article,
                                 :image,
                                 :image_cache,
                                 :subscription,
                                 :accept_terms,
                                 :professional,
                                 :imprint,
                                 :terms,
                                 :terms_and_revocation_are_chosen,
                                 :about_me,
                                 :about_my_shop,
                                 :withdrawal_form_id,
                                 :package,
                                 :set_shipping,
                                 :set_payment_types,
                                 :main_picture_id,
                                 payment_type_ids:[],
                                 no_shipping_to_the_countries: [],
                                 bank_transfer_data_attributes:[
                                   :id,
                                   :bank_transfer,
                                   :account_holder,
                                   :account_number,
                                   :bank_code,
                                   :bank_name,
                                   :iban,
                                   :swft_bic],
                                 personal_bank_data_attributes:[
                                   :id,
                                   :bank_transfer,
                                   :account_holder,
                                   :account_number,
                                   :bank_code,
                                   :bank_name,
                                   :iban,
                                   :swft_bic],
                                 paypal_data_attributes:[
                                   :id,
                                   :client_id,
                                   :client_secret],
                                 shipping_methods_attributes:[
                                   :id,
                                   :checked,
                                   :name,
                                   :price,
                                   :duration_from,
                                   :duration_to,
                                   :_destroy],
                                 shipping_readiness_attributes:[
                                   :readiness,
                                   :from,
                                   :to],
                                 address_attributes:[
                                   :id,
                                   :occupation,
                                   :country,
                                   :postal_code,
                                   :street,
                                   :first_name,
                                   :last_name,
                                   :place,
                                   :house_number,
                                   :show_to_public,
                                   :phone,
                                   :mobile,
                                   :show_phone_to_public,
                                   :area_code])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_about_me_template.html.slim
  h4.inblock style="margin:0px 5px;"
    = t '.short_description'
    '
    .glyphicon.glyphicon-info-sign data-toggle="popover" data-trigger="hover" data-content="#{t '.info_box.short_description'}"
  div
    .green_button.replaceable_button
      .circles
        .circle1
        .circle2
        .circle3
        .circle4
      = submit_tag t('.edit')
    .clear
      = label_tag :about_me, t('.about_me'), style: "margin-left:10px"
      br
      = text_area_tag :about_me, @shop.about_me, disabled: "disabled"   
  .display_none
    = form_for @shop do |f|
      .green_button
        .circles
          .circle1
          .circle2
          .circle3
          .circle4
        = f.submit t('.save'),
            name: :about_me,
            data: { disable_with: t('.save') }
      .clear
        = f.label :about_me, style: "margin-left:10px"
        br
        = f.text_area :about_me
  hr
  div
    .green_button.replaceable_button
      .circles
        .circle1
        .circle2
        .circle3
        .circle4
      = submit_tag t('.edit')
    .clear
      = label_tag :about_me, t('.about_my_shop'), style: "margin-left:10px"
      br
      = text_area_tag :about_me, @shop.about_my_shop, disabled: "disabled"
  .display_none
    = form_for @shop do |f|
      .green_button
        .circles
          .circle1
          .circle2
          .circle3
          .circle4
        = f.submit t('.save'),
            name: :about_me,
            data: { disable_with: t('.save') }
      .clear
        = f.label :about_my_shop, style: "margin-left:10px"
        br
        = f.text_area :about_my_shop
  hr
  div
    .green_button.replaceable_button
      .circles
        .circle1
        .circle2
        .circle3
        .circle4
      = submit_tag t('.edit')
    .clear
      h4.inblock style="margin:0px 5px 0px 0px"
        = t '.pictures'
        '
        .glyphicon.glyphicon-info-sign data-toggle="popover" data-trigger="hover" data-content="#{t '.info_box.pictures'}"
    br
    .about_me_shops_image
      h5 = t '.profile_picture'
      = image_tag @shop.main_picture_small_url
      br
    .about_me_shops_pictures
      h5 = t '.shop_images'
      - @shop.pictures.each do |picture|
        = image_tag picture.image.small.url if picture.image?
        '
  .display_none
    = form_for @shop do |f|
      .green_button
        .circles
          .circle1
          .circle2
          .circle3
          .circle4
        = f.submit t('.save'),
            name: :update_shop_images,
            data: { disable_with: t('.save') }
      h4.clear style="margin:0px"
        = t '.pictures'
        '
        .glyphicon.glyphicon-info-sign data-toggle="popover" data-trigger="hover" data-content="#{t '.info_box.pictures'}"
      br
      .about_me_shops_image.main_picture_block
        h5 = t '.profile_picture'
        = f.hidden_field :main_picture_id, value: nil
        - if @shop.main_picture.present?
          = render partial: 'main_pictures/picture_edit',
              locals: { main_picture: @shop.main_picture }
        #add_main_picture_button
          .glyphicon.glyphicon-plus
        = image_tag 'loading.gif', class: 'loading'
      .about_me_shops_pictures.inblock_top#pictures_place
        h5 = t '.shop_images'
        = image_tag 'loading.gif', class: 'loading'
        #add_picture.inblock_top
          #add_picture_button
            .glyphicon.glyphicon-plus
          #add_picture_text = t '.another_image'
  .display_none
    = render partial: "pictures/form"
    #hidden_pictures = render partial: 'pictures/picture_edit',
                        collection: @shop.pictures,
                        as: :picture
    = render 'main_pictures/form'

app/views/shops/about_me.html.slim
- content_for :title, t('.head_title')
= render "left_menu"
.usual_body.about_me_shops.shop_edit
  = render "shops/edit_shop_headings"
  = render "shops/about_me_template"

app/views/shops/change_image.html.erb
<h1>Shopbild ändern</h1>

<h2>Altes Bild</h2>
<%= image_tag @shop.image_url %>

<h2>Neues Bild</h2>
<%= form_for(@shop, html: {multipart: true}) do |f| %>
    <% if @shop.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this article from being saved:</h2>
          <ul>
            <% @shop.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

    <div class="field">
      <%= f.submit, data: { disable_with: 'submit' } %>
    </div>
<% end %>

<%= link_to t('back'), @shop %>

app/views/shops/edit.html.slim
- content_for :title, t('.head_title')
= render 'form'

app/views/shops/left_shop_info_panel.html.slim
.left_shop_info_panel
  = image_tag @shop.main_picture_url,
    class: 'main_picture'
  .shop_name
    = link_to (t '.shop_by', user: @user.nickname) + ' ' + @shop.name, root_url(subdomain: @shop.subdomain)
  .info_box
    .about_shop
      = t '.about_shop', shop: @shop.name
    .rating_field
      = link_to ratings_shop_url(@shop)
        .stars
          - (1..5).each do |i|
            - if i <= @user.average_rating.to_i
              = image_tag 'star_white_full.png'
            - elsif @user.float_rating.present? && @user.float_rating > 0 && @user.average_rating.floor + 1 == i
              span style='width:#{2 + (0.18 * @user.float_rating)}px'
                = image_tag 'star_white_full.png'
              = image_tag 'star_white.png'
            - else
              = image_tag 'star_white.png'
                
        .rating_count = @user.rating_count
    
    .statistics_mobile_toggle
      .statistics_mobile_header
        span = t '.shop_details'
      .statistics_mobile_content
        table.statistics
          tr
            td = t '.shop_fans'
            td = @shop.favorite_shops.count
          tr
            td = t '.online_articles'
            td = @shop.articles.normal.online.count
          tr
            td = t '.sold_articles'
            td = @shop.articles.normal.sold.count
          tr.date_large
            td = t '.date_of_creation'
            td = l @shop.created_at.to_date
          tr.date_small
            td colspan='2'
              = t '.date_of_creation'
              '
              = l @shop.created_at.to_date
            
        .shop_meta_links
          .terms = t '.terms'
          .imprint = t '.imprint'
          .revocation = t '.revocation'
          
      - if @address.show_to_public? && user_signed_in?
        .address
          .address_header
            span = t '.address'
          .address_content
            = @address.street
            '
            = @address.house_number
            br
            = @address.postal_code
            '
            = @address.place
            br
            = @address.country_name
            - if @address.show_phone_to_public
              - if @address.phone?
                br
                = @address.area_code
                '
                = @address.phone
              - if @address.mobile?
                br
                = @address.area_code
                '
                = @address.mobile
        
  - if current_or_guest_user.favorite_shops.find_by(shop_id: @shop.id).nil?
    .shop_favorites_add = link_to t(".add_shop_to_favorites"), {controller: :favorite_shops, action: :create, shop_id: @shop.id}, method: :post
  - else
    .shop_favorites_remove = link_to t('.remove_from_favorite_shops'),
      favorite_shop_url(current_or_guest_user.favorite_shops.find_by(shop_id: @shop.id)),
      method: :delete
  - if !current_page?(ratings_shop_path(@shop)) && user_signed_in?
    .send_message
      = link_to t('.to_contact'), new_message_url( recipient: @shop.name, article_title: (@article.present? ? @article.title : ''))
  - elsif current_page?(ratings_shop_path(@shop))
  
    .rating_details
      - [5,4,3,2,1].each do |rating|
        .rating_field
          = link_to ratings_shop_url(@shop, rating: rating, displays: params[:displays])
            .stars
              - (1..5).each do |i|
                - if i <= rating
                  = image_tag 'star_blue_full.png'
                - else
                  = image_tag 'star_blue.png'
              '
            .rating_count = @user.rating_count(rating)
            
    .displays
      = form_tag ratings_shop_url(@shop), method: :get do |f|
        = hidden_field_tag :rating, params[:rating]
        = label_tag :displays, t('.displays:')
        = select_tag :displays,
            options_for_select(['all', 'buyer', 'seller'].collect{ |n| [t('.' + n), n]}, params[:displays]),
            {onchange: "this.form.submit()" }
      .clear
  

app/views/shops/new.html.slim
- content_for :title, t('.head_title')
= render file: 'shops/_form'

app/views/shops/ratings.html.slim
- content_for :title, t('.head_title')
.shop_ratings
  .upper_page_links
    ' > #{t '.shops'} >
    = link_to @shop.user.full_name,
        root_url(subdomain: @shop.subdomain)
    '  >
    = link_to t('.reviews'), ratings_shop_url(@shop, subdomain: @shop.subdomain)
  .table-cell-top
    = render file: 'shops/left_shop_info_panel'
  .ratings.table-cell-top
    - if @reviews.present?
      table
        thead
          tr
            td.rating_and_comment
            td.seller_or_buyer
            td.reviewed_by = t '.reviewed_by'
            td.article_title = t '.articles'
            td.date = t '.reviewed_at'
        tbody
          - @reviews.each do |review|
            - if review.from == "buyer"
              tr.first_row
                td
                  .rating_field
                    .stars
                      - (1..5).each do |i|
                        - if i <= review.score
                          .gold_star &#9733;
                        - else
                          .gray_star &#9733;
                      '
                td.black
                  | (#{t '.buyer'})
                td.black = review.articles_order.buyer.nickname
                td.darkgray = review.articles_order.article.title
                td = l review.updated_at.to_date
              tr.last_row
                td.black = t ".comment:"
                td.gray colspan="4" = review.text
            - else
              tr.first_row
                td
                  .rating_field
                    .stars
                      - (1..5).each do |i|
                        - if i <= review.score
                          .gold_star &#9733;
                        - else
                          .gray_star &#9733;
                      '
                td.link_to_seller
                  = link_to root_url(subdomain: review.articles_order.seller.shop.subdomain)
                    | (#{t '.seller'})
                td.black = review.articles_order.seller.nickname
                td.darkgray = review.articles_order.article.title
                td = l review.updated_at.to_date
              tr.last_row
                td.black = t ".comment:"
                td.gray colspan="4" = review.text
    - else
      div = t '.no_comments'

app/views/shops/show.html.slim
- content_for :title, @shop.name
.shop_show
  #upper-path
    = image_tag 'arrow_to_left.png'
    = link_to 'Jakira', 
      root_url,
      class: 'without-underline-if-mobile'
    span &nbsp;&bull;&nbsp;
    ' #{t '.shops'}
    span &nbsp;&bull;&nbsp;
    = link_to @shop.user.full_name, 
      root_url(subdomain: @shop.subdomain),
      class: 'without-underline-if-mobile'
      
  h1.shop_title #{@shop.user.address.full_name}
  
  .table-cell-top
    = render file: 'shops/left_shop_info_panel'
  .central_content
    .shop_data
      .shop_info
        .images
          - @shop.pictures.each do |picture|
            - if picture.image?
              .shop_picture
                = image_tag picture.image.middle.url, class: "img-responsive"
        .info_text_block.info_text_block_shop
          .info_text_header
            h2 = t '.about_my_shop'
          .info_text_content
            = @shop.about_my_shop
        .info_text_block.info_text_block_about
          .info_text_header
            h2 = t '.about_me'
          .info_text_content
            = @shop.about_me
          
        .info_text_block
          .terms_content
            h4 = t '.terms_'
            = @shop.terms
            br
            = t '.platform_of_the_european_commission_for_online_dispute_resolution'
            '
            = auto_link("www.ec.europa.eu/consumers/odr", html: { target: '_blank' })
          .imprint_content
            h4 = t '.imprint_'
            = @shop.imprint
            br
            = t '.platform_of_the_european_commission_for_online_dispute_resolution'
            '
            = auto_link("www.ec.europa.eu/consumers/odr", html: { target: '_blank' })
          .revocation_content
            h4 = t '.revocation_'
            h5 = t '.physical'
            = @shop.revocation_physical_products
            h5 = t '.service'
            = @shop.revocation_services
            h5 = t '.digital'
            = @shop.revocation_digital_content
    - if current_or_guest_user.favorite_shops.find_by(shop_id: @shop.id).nil?
      .shop_favorites_add = link_to t(".add_shop_to_favorites"), {controller: :favorite_shops, action: :create, shop_id: @shop.id}, method: :post
    - else
      .shop_favorites_remove = link_to t('.remove_from_favorite_shops'),
        favorite_shop_url(current_or_guest_user.favorite_shops.find_by(shop_id: @shop.id)),
        method: :delete
    - if !current_page?(ratings_shop_path(@shop)) && user_signed_in?
      .send_message
        = link_to t('.to_contact'), new_message_url( recipient: @shop.name, article_title: (@article.present? ? @article.title : ''))
    - if @articles.present?
      h3 #{t '.products_by'} #{@shop.user.address.full_name}
      .shop_articles
        - @articles.each do |article|
          = render partial: 'articles/categories_article_block',
              locals: {article: article}