config/routes.rb
WeltDerUnikate::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  constraints subdomain: 'administration' do
    namespace(:admin, path: '/') do
      get '/' => :show
      get :maillog
      resources :art_associations, except: [:destroy, :show]
      resources :members do
        get :update_monthly_charge_for_all_users
        member do
          get :purchases_and_sales
          get :user_profile
          get :user_settings
          get "shop_profile/about_me"           => :shop_profile_about_me
          get "shop_profile/settings"           => :shop_profile_settings
          get "shop_profile/terms_and_imprint"  => :shop_profile_terms_and_imprint
          get "shop_profile/revocation"         => :shop_profile_revocation
          post :update_user_data
          get :update_monthly_charge_for_the_user
          get :restore_deleted_account
        end
      end
      resources :invoices, only: [] do
        collection do
          get :created
          get :open
          get :paid
          get :cancellations
          get :credits
          get :check_boxes_action
          get :send_monthly_invoice
          get :send_commission_invoice
        end
      end
      resources :correspondence, only: [:index] do
        collection do
          get :registration
          get :new_shop
          get :to_old_email_about_email_changing
          get :confirmation_email
          get :password_changed
          get :articles_order_dispatched
          get :article_is_already_sold
          get :new_order_message_from_buyer
          get :new_order_message_from_seller
          get :buyer_cancellation
          get :seller_cancellation
          get :new_message
          get :purchase_notification_confirmed_to_buyer
          get :purchase_notification_confirmed_to_seller
          get :purchase_notification_unconfirmed_to_buyer
          get :purchase_notification_unconfirmed_to_seller
          get :share_article
          get :new_voucher
        end
      end
      resources :newsletters, only: [:new, :create]
      resources :business_cards, only: [:index] do
        post :change_details, on: :member
      end
      resources :vouchers, only: :index do
        get :change, on: :collection
        member do
          post :change_status
          post :change_paid_on
        end
      end
      get :text_content
      scope :text_content do
        resources :faq_sections,
            param: :faq_section_id do
          member do
            resources :faq_questions,
                param: :faq_question_id,
                except: :index
          end
        end
        get :discover_the
        get :find_yours
      end
    end
  end

  get 'admin', to: redirect(subdomain: 'administration', path: '/')
  get 'admin/:any', to: redirect(subdomain: 'administration', path: '/%{any}')

  constraints subdomain: false do
    resources :invoices, only: [:index, :show]
  end
  resources :invoices, only: [] do
    get :pdf_version, on: :member
  end

  resources :favorites, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :articles_view_types, only: [] do
    get :change, on: :collection
  end

  resources :messages, except: [:index] do
    member do
      get :reply
      get :to_trash
    end
    collection do
      get  :inbox
      get  :sent
      get  :drafts
      get  :bin
      get  :archive
      post :check_boxes_action
      get  :empty_trash
    end
  end

  resources :orders do
    collection do
      get :open
      get :completed
      get :canceled
    end
  end

  resources :purchases do
    member do 
      get  :addresses_and_payment_types
      get  :check_order
      get  :complete
    end
    collection do
      get :open
      get :completed
    end
  end

  resources :articles, except: :index do
    post :change, on: :member
    collection do
      get :sold
      get :deleted
      get :delete_all
      get :online
      get :offline
      get :templates
    end
  end


  resources :documents

  scope :search do
    get '/:search', to: 'articles#search'
    get '/', to: 'articles#search'
  end

  resources :payment_infos
  resources :payment_selections
  resources :shipping_methods
  resources :pictures, only: [:create, :destroy, :edit] do
    post :crop, on: :member
    post :create_shop_main, on: :collection
  end

  resources :withdrawal_forms, only: [:create, :destroy] do
    get :preview, on: :member
  end

  resources :shopping_baskets, only: [:create,
                                      :index,
                                      :update,
                                      :destroy]

  resources :articles_orders, only: [:destroy] do
    member do
      get :paypal_payment
      get :bank_details
      get :credit_card_payment
      post :credit_card_payment
      get :write_a_review
      get :write_a_review_for_buyer
      get :mark_as_sold
      get :mark_order_messages_as_read
      patch :use_voucher
      patch :set_payment_type
      patch :set_pickup_as_shipping_method
      patch :use_shipping_address
      get :closure_confirmation
      get :close
      get :cancel
      patch :update_status
      get :send_payment_reminder
    end
  end

  resources :credit_card_data, only: [:create]

  get '/' => 'shops#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www"}

  controller :pages do
    root to: :home
    get :imprint
    get :privacy
    get :about_jakira
    get :terms
  end

  resources :categories, only: :show

  devise_for :users, controllers: {registrations: 'users/registrations',
                                   sessions: 'users/sessions',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations',
                                   omniauth_callbacks: "users/omniauth_callbacks"}
  # devise_scope :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end

  resources :ratings, only: [:update, :index]

  resources :shops, except: [:edit, :index] do
    collection do
      get :about_me
      get :settings
      get :terms_and_imprint
      get :revocation
      get :open
    end
    member do
      get :show_terms
      get :show_revocation
      get :ratings
      get :download_withdrawal_form
    end
  end

  resources :order_messages, only: [:create, :show]
  resources :share, only: [:new, :create, :index]

  resources :business_cards, only: [:index, :create]

  resources :vouchers, only: [:show, :new, :create] do
    get :after_payment, on: :collection
    get :pdf_version, on: :member
  end

  resources :main_voucher_data, only: :update

  resources :addresses, only: [] do
    get :load_country_code, on: :collection
    member do
      post :update_purchase_address
    end
  end

  resources :art_associations,
      only: [:create, :index] do
    collection do
      get :register
      patch :become_a_member
      scope :admin_panel, as: 'admin_panel' do
        get :events
        get :settings
        scope as: 'art_associations' do
          resources :members,
              controller: 'art_associations/members',
              except: [:show, :destroy] do
            post :import_xls, on: :collection
          end
        end
      end
    end
  end

  resources :faq, only: [:index, :show]

  get '/contact', to: 'contacts#new'
  resources :contacts, only: [:create]
end

app/models/shipping_method.rb
# An Article can have multiple ShippingOptions. The buyer will select one.
class ShippingMethod < ActiveRecord::Base

  after_save :destroy_if_not_checked

  belongs_to :shipping_methodable, polymorphic: true, touch: true
  has_many :articles_orders

  monetize :price_cents

  validates_acceptance_of :checked, if: :shipping_methods_were_not_chosen?
  
  validates :price_cents,
              numericality: { greater_than_or_equal_to: 0 },
              if: -> { checked && name != "pickup" && name != "free_within_germany"}

  validate :validate_duration

  validates :name,
    inclusion: { in: %w{pickup free_within_germany within_germany within_eu worldwide} },
    presence: true,
    uniqueness: { scope: :shipping_methodable_id}

  def destroy_if_not_checked
  	if !self.checked
  	  self.destroy
  	end
  end

  def shipping_methods_were_not_chosen?
    (shipping_methodable.class.to_s == "Article" ||
      shipping_methodable.set_shipping == '1') &&
    !shipping_methodable.shipping_methods.map(&:checked).include?(true)
  end

  def duration
    if duration_from.nil? || duration_to.nil?
      I18n.t('shipping_method.duration.by_appointment')
    else
      duration_from.to_s + ' - ' + duration_to.to_s + I18n.t('shipping_method.duration.days')
    end
  end

  private

  def validate_duration
    if checked && name != "pickup"
      if duration_from.nil? ||
        duration_from < 0 ||
        duration_from == 0 ||
        (duration_to.present? && (duration_from >= duration_to && duration_to != 0))
        errors.add(:duration, I18n.t("activerecord.errors.models.shipping_method.attributes.validate_duration.valid") )
        errors.add(:duration_from, nil)
      end
      if duration_to.nil? ||
        duration_to <= 0 ||
        (duration_from.present? && duration_from >= duration_to)
        errors.add(:duration, I18n.t("activerecord.errors.models.shipping_method.attributes.validate_duration.valid") )
        errors.add(:duration_to, nil)
      end
    end
  end
end

app/controllers/shipping_methods_controller.rb
class ShippingMethodsController < ApplicationController
  before_action :set_shipping_method, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  authorize_resource

  # GET /shipping_methods
  # GET /shipping_methods.json
  def index
    @shipping_methods = ShippingMethod.all
  end

  # GET /shipping_methods/1
  # GET /shipping_methods/1.json
  def show
    @shipping_method.destroy
    redirect_to :back
  end

  # GET /shipping_methods/new
  def new
    @shipping_method = ShippingMethod.new
  end

  # GET /shipping_methods/1/edit
  def edit
  end

  # POST /shipping_methods
  # POST /shipping_methods.json
  def create
    @shipping_method = ShippingMethod.new(shipping_method_params)
    #@shipping_method.article_id = current_user.shop.default_article_id

    respond_to do |format|
      if @shipping_method.save
        format.html { redirect_to @shipping_method, notice: 'Shipping method was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shipping_method }
      else
        format.html { render action: 'new' }
        format.json { render json: @shipping_method.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /shipping_methods/1
  # PATCH/PUT /shipping_methods/1.json
  def update
    respond_to do |format|
      if @shipping_method.update(shipping_method_params)
        format.html { redirect_to @shipping_method.article, notice: 'Shipping method was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shipping_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipping_methods/1
  # DELETE /shipping_methods/1.json
  def destroy
    # article = @shipping_method.article
    @shipping_method.destroy
    redirect_to :back
    # respond_to do |format|
    #   format.html { redirect_to :back }
    #   format.json { head :no_content }
    #   format.js
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipping_method
      @shipping_method = ShippingMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipping_method_params
      params[:shipping_method].permit(:name, :duration, :price, :article_id)
    end
end

app/helpers/shipping_methods_helper.rb
module ShippingMethodsHelper
end

app/views/shipping_methods/_form.html.slim
table#shipping-methods
  thead
    td colspan='4' = t '.shipping'
    td colspan='4' = t '.delivery_times'
  - f.object.shipping_methods.each do |shipping_method|
    = f.fields_for :shipping_methods, shipping_method do |ff|
      = ff.hidden_field :name, value: shipping_method.name
      tr id="#{ff.object.name}"
        td.label_cell = ff.check_box :checked
        - if !["pickup", "free_within_germany"].include?(shipping_method.name)
          td = ff.label :checked, t(ff.object.name)
          td.input_field = ff.text_field :price
          td.price_cell = ff.label :price, "Euro"
        - else
          td.first colspan='3' = ff.label :checked, t(ff.object.name)
        - if shipping_method.name == "pickup"
          td colspan='4' = t '.by_appointment'
        - else
          td.input_field = ff.text_field :duration_from
          td = t '.to'
          td.input_field = ff.text_field :duration_to
          td = t '.working_days'

app/views/shipping_methods/_hover_table.html.slim
.shipping_methods_hover
  .arrow_up_borders
  .arrow_up
  .table_wrapper
    .header = t '.terms_of_delivery'
    table
      thead
        tr
          th = t '.shipping_method'
          th = t '.shipping_costs'
          th = t '.delivery_times'
      - article.shipping_methods.where(checked: true).each do |shipping_method|
        tr
          td data-title = t('.shipping_method')
            = t shipping_method.name
          td data-title = t('.shipping_costs')
            - if shipping_method.name != "pickup" && shipping_method.name != "free_within_germany"
              = t shipping_method.price
              |  &euro;
          td data-title = t('.delivery_times')
            - if shipping_method.name == "pickup"
              = t '.by_appointment'
            - else
              = shipping_method.duration_from
              '
              = t '.to'
              ' 
              = shipping_method.duration_to
              '
              = t '.working_days'

app/views/shipping_methods/_nested_form.html.erb
<div id="<%= f.object.name %>">
  <div class="shop_form_shipping_method_name_and_check">
    <div class="field">
      <%= f.check_box :checked %>
      <%= f.label :checked, t(f.object.name) %>
    </div>
    <div class="field">
      <%= f.hidden_field :name, value: shipping_method.name %>
    </div>
  </div>
  <% if shipping_method.name != "pickup" && shipping_method.name != "free_within_germany"%> 
    <div class="field">
      <%= f.text_field :price %>
      <%= f.label :price, "Euro" %>
    </div>
  <% end %>
</div>

app/views/shipping_methods/_shipping_method.html.erb
<%= div_for shipping_method do %>
  <%= shipping_method.name %>
  <%= humanized_money_with_symbol shipping_method.price %>
  <%= shipping_method.duration %>
  <%= link_to t('Delete'), shipping_method, method: :delete, remote: true %>
<% end %>

app/views/shipping_methods/create.js.erb
$('div#shipping_methods').append("<%= escape_javascript(render @shipping_method) %>");
$('div#<%= dom_id(@shipping_method) %>').effect('highlight');

app/views/shipping_methods/destroy.js.erb
$('#<%= dom_id(@shipping_method) %>').fadeOut();

app/views/shipping_methods/edit.html.erb
<h1>Editing shipping method</h1>

<%= render 'form' %>

<%= link_to 'Back', @shipping_method.article %>

app/views/shipping_methods/index.html.erb
<h1>Listing shipping_methods</h1>

<div id="shipping_methods">
  <%= render @shipping_methods %>
</div>

<br>

<%= link_to 'New Shipping method', new_shipping_method_path %>

app/views/shipping_methods/new.html.erb
<h1>New shipping method</h1>

<%= render 'form' %>

<%= link_to 'Back', current_user.shop.default_article %>

app/views/shipping_methods/show.html.erb
<%= link_to 'Edit', edit_shipping_method_path(@shipping_method) %> |
<%= link_to 'Back', shipping_methods_path %>