config/routes.rb
WeltDerUnikate::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  constraints subdomain: 'administration' do
    namespace(:admin, path: '/') do
      get '/' => :show
      get :maillog
      resources :art_associations, except: [:destroy, :show]
      resources :members do
        get :update_monthly_charge_for_all_users
        member do
          get :purchases_and_sales
          get :user_profile
          get :user_settings
          get "shop_profile/about_me"           => :shop_profile_about_me
          get "shop_profile/settings"           => :shop_profile_settings
          get "shop_profile/terms_and_imprint"  => :shop_profile_terms_and_imprint
          get "shop_profile/revocation"         => :shop_profile_revocation
          post :update_user_data
          get :update_monthly_charge_for_the_user
          get :restore_deleted_account
        end
      end
      resources :invoices, only: [] do
        collection do
          get :created
          get :open
          get :paid
          get :cancellations
          get :credits
          get :check_boxes_action
          get :send_monthly_invoice
          get :send_commission_invoice
        end
      end
      resources :correspondence, only: [:index] do
        collection do
          get :registration
          get :new_shop
          get :to_old_email_about_email_changing
          get :confirmation_email
          get :password_changed
          get :articles_order_dispatched
          get :article_is_already_sold
          get :new_order_message_from_buyer
          get :new_order_message_from_seller
          get :buyer_cancellation
          get :seller_cancellation
          get :new_message
          get :purchase_notification_confirmed_to_buyer
          get :purchase_notification_confirmed_to_seller
          get :purchase_notification_unconfirmed_to_buyer
          get :purchase_notification_unconfirmed_to_seller
          get :share_article
          get :new_voucher
        end
      end
      resources :newsletters, only: [:new, :create]
      resources :business_cards, only: [:index] do
        post :change_details, on: :member
      end
      resources :vouchers, only: :index do
        get :change, on: :collection
        member do
          post :change_status
          post :change_paid_on
        end
      end
      get :text_content
      scope :text_content do
        resources :faq_sections,
            param: :faq_section_id do
          member do
            resources :faq_questions,
                param: :faq_question_id,
                except: :index
          end
        end
        get :discover_the
        get :find_yours
      end
    end
  end

  get 'admin', to: redirect(subdomain: 'administration', path: '/')
  get 'admin/:any', to: redirect(subdomain: 'administration', path: '/%{any}')

  constraints subdomain: false do
    resources :invoices, only: [:index, :show]
  end
  resources :invoices, only: [] do
    get :pdf_version, on: :member
  end

  resources :favorites, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :articles_view_types, only: [] do
    get :change, on: :collection
  end

  resources :messages, except: [:index] do
    member do
      get :reply
      get :to_trash
    end
    collection do
      get  :inbox
      get  :sent
      get  :drafts
      get  :bin
      get  :archive
      post :check_boxes_action
      get  :empty_trash
    end
  end

  resources :orders do
    collection do
      get :open
      get :completed
      get :canceled
    end
  end

  resources :purchases do
    member do 
      get  :addresses_and_payment_types
      get  :check_order
      get  :complete
    end
    collection do
      get :open
      get :completed
    end
  end

  resources :articles, except: :index do
    post :change, on: :member
    collection do
      get :sold
      get :deleted
      get :delete_all
      get :online
      get :offline
      get :templates
    end
  end


  resources :documents

  scope :search do
    get '/:search', to: 'articles#search'
    get '/', to: 'articles#search'
  end

  resources :payment_infos
  resources :payment_selections
  resources :shipping_methods
  resources :pictures, only: [:create, :destroy, :edit] do
    post :crop, on: :member
    post :create_shop_main, on: :collection
  end

  resources :withdrawal_forms, only: [:create, :destroy] do
    get :preview, on: :member
  end

  resources :shopping_baskets, only: [:create,
                                      :index,
                                      :update,
                                      :destroy]

  resources :articles_orders, only: [:destroy] do
    member do
      get :paypal_payment
      get :bank_details
      get :credit_card_payment
      post :credit_card_payment
      get :write_a_review
      get :write_a_review_for_buyer
      get :mark_as_sold
      get :mark_order_messages_as_read
      patch :use_voucher
      patch :set_payment_type
      patch :set_pickup_as_shipping_method
      patch :use_shipping_address
      get :closure_confirmation
      get :close
      get :cancel
      patch :update_status
      get :send_payment_reminder
    end
  end

  resources :credit_card_data, only: [:create]

  get '/' => 'shops#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www"}

  controller :pages do
    root to: :home
    get :imprint
    get :privacy
    get :about_jakira
    get :terms
  end

  resources :categories, only: :show

  devise_for :users, controllers: {registrations: 'users/registrations',
                                   sessions: 'users/sessions',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations',
                                   omniauth_callbacks: "users/omniauth_callbacks"}
  # devise_scope :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end

  resources :ratings, only: [:update, :index]

  resources :shops, except: [:edit, :index] do
    collection do
      get :about_me
      get :settings
      get :terms_and_imprint
      get :revocation
      get :open
    end
    member do
      get :show_terms
      get :show_revocation
      get :ratings
      get :download_withdrawal_form
    end
  end

  resources :order_messages, only: [:create, :show]
  resources :share, only: [:new, :create, :index]

  resources :business_cards, only: [:index, :create]

  resources :vouchers, only: [:show, :new, :create] do
    get :after_payment, on: :collection
    get :pdf_version, on: :member
  end

  resources :main_voucher_data, only: :update

  resources :addresses, only: [] do
    get :load_country_code, on: :collection
    member do
      post :update_purchase_address
    end
  end

  resources :art_associations,
      only: [:create, :index] do
    collection do
      get :register
      patch :become_a_member
      scope :admin_panel, as: 'admin_panel' do
        get :events
        get :settings
        scope as: 'art_associations' do
          resources :members,
              controller: 'art_associations/members',
              except: [:show, :destroy] do
            post :import_xls, on: :collection
          end
        end
      end
    end
  end

  resources :faq, only: [:index, :show]

  get '/contact', to: 'contacts#new'
  resources :contacts, only: [:create]
end

app/models/user.rb
# This Model manages User accounts. It is coupled with devise and allows email confirmation,
# locking after too many unsuccessful login attempts, validates the user input and tracks some
# activity about the user like the login count.
class User < ActiveRecord::Base

  enum articles_view_type: [:vertical, :horizontal]
  enum role: [:guest, :regular, :admin, :art_association]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         # :lockable,
         :omniauthable,
         :confirmable,
         :timeoutable, timeout_in: 1.hours,
          authentication_keys: [:login]

  attr_accessor :account_type,
                :current_password,
                :accept_terms,
                :accept_privacy_policy,
                :login,
                :become_a_member

  before_create :add_membership_number,
                if: -> { regular? }

  # before_save :add_art_association_membership_number,
  #   if: -> { art_association.present? &&
  #            art_association_membership_number.nil?}

  after_commit :update_business_cards_thumbs, if: -> { has_shop? }

  belongs_to :address
  belongs_to :art_association
  has_many :articles
  has_many :shopping_baskets
  has_many :cart_articles,
             through: :shopping_baskets,
             source: :article
  has_many :favorites
  has_many :favorite_articles,
             through: :favorites,
             source: :article
  has_many :orders, foreign_key: 'seller_id'
  has_many :purchases
  has_many :articles_orders, through: :purchases
  has_many :sales,
             through: :orders,
             source: :articles_orders
  has_many :favorite_shops
  has_many :invoices
  has_many :order_messages
  
  has_many :uploaded_pictures,
           class_name: 'Image',
           foreign_key: :uploader_id

  has_many :pictures,
           -> { user_pictures },
           class_name: 'Image',
           foreign_key: :parent_id

  has_many :business_cards_orders
  # has_many :sent_messages, class_name: "Message", foreign_key: 'sender_id'
  # has_many :received_messages, class_name: "Message", foreign_key: 'recipient_id'

  has_many :received_ratings,
           class_name: 'Rating',
           foreign_key: "receiver_id"

  has_many :sent_ratings,
           class_name: 'Rating',
           foreign_key: "sender_id"

  has_one :shop

  accepts_nested_attributes_for :shop, :address

  validates_presence_of :art_association_membership_number,
                        :art_association,
                        if: -> { become_a_member }

  validates :art_association_membership_number,
            numericality: { greater_than: 0 },
            allow_nil: false,
            if: -> { become_a_member }

  validates :art_association_membership_number,
            numericality: { greater_than: 0 },
            allow_nil: true,
            if: -> { !become_a_member }

  validates_uniqueness_of :art_association_membership_number,
                            scope: :art_association_id,
                            if: -> { art_association.present? || become_a_member }

  validates :accept_terms,
            :accept_privacy_policy,
              acceptance: true

  # validates_presence_of :nickname,
  #                         unless: -> { art_association.present? }

  validates :nickname,
              uniqueness: true,
              format: {with: /^[a-zA-Z0-9_\.]*$/,
                       multiline: true},
              allow_blank: true,
                if: -> { !guest? }

  validates_presence_of :address,
                          if: -> { regular? || art_association? }


  scope :newsletter_receivers, -> { regular
                                   .where(monthly_letters_notification: true)}

  scope :sellers, -> { joins(:shop)
                      .where(shops: {deleted: false}) }

  scope :buyers, -> { regular
                     .where("not exists (
                             select null 
                             from shops
                             where users.id = shops.user_id 
                             and shops.deleted != 't')")}

  scope :search, lambda { |text|
    if text
       includes(:address)
      .where('LOWER(users.nickname) LIKE :search 
           OR LOWER(users.email) LIKE :search
           OR LOWER(addresses.company_name) LIKE :search
           OR LOWER(addresses.first_name) LIKE :search
           OR LOWER(addresses.last_name) LIKE :search',
           search: "%#{text.downcase}%")
      .references(:address)
    else
      all
    end
  }

  def rating_count(rating=nil)
    if (1..5).exclude?(rating)
      self.received_ratings.finished.count
    else
      self.received_ratings.finished.where(score: rating).count
    end
    
  end

  def average_rating
    self.received_ratings.finished.map(&:score).sum.to_f / self.rating_count if self.received_ratings.finished.present?
  end

  def float_rating
    ((average_rating - average_rating.floor) * 100).to_i if self.average_rating.present? 
  end

  def full_name
    address.full_name
  end

  def has_shop?
    !shop.blank? && !shop.new_record? && !shop.deleted?
  end

  alias seller? has_shop?

  def buyer?
    regular? && !has_shop?
  end

  def buyer_or_guest?
    buyer? || guest?
  end

  def regular_or_guest?
    regular? || guest?
  end

  def email_from
    full_name + ' <' + email + '>'
  end

  def remember_me
    true
  end

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).last
    if user.present? && !user.deleted
      user
    else
      u = User.new(provider: auth.provider,
                   uid: auth.uid,
                   nickname: auth.info.name,
                   email: "temporary_#{Time.now.to_i}#{rand(100)}@email.com")
      u.skip_confirmation!
      u.build_address
      u.save!(validate: false)
      u
    end
  end

  def has_unread_messages?
    Message.received(self).not_read.count > 0
  end

  def self.members_to_xls(options = {})
    CSV.generate(options) do |csv|
      user_columns = ["art_association_membership_number",
                      "nickname",
                      "email"]
      address_columns = ["first_name",
                         "last_name",
                         "street",
                         "house_number",
                         "postal_code",
                         "place",
                         "country"]
      csv << user_columns + address_columns
      all.each do |user|
        csv << user.attributes.values_at(*user_columns) + user.address.attributes.values_at(*address_columns)
      end
    end
  end

  def occupation
    has_shop? ? shop.address.occupation : nil
  end

  def full_name_occupation
    full_name + (occupation.present? ? " - #{occupation}" : '')
  end

  def address_and_contact_data_for_business_card
    address_for_business_card +
    "\n" +
    contact_data_for_business_card
  end

  def address_for_business_card
    "#{shop.address.street} #{shop.address.house_number}" +
    "\n#{shop.address.postal_code} #{shop.address.place}"
  end

  def contact_data_for_business_card
    (shop.address.phone.present? ?
      "#{I18n.t('user.address_for_business_card.phone')} #{shop.address.phone_number}\n" :
      '') +
    (shop.address.mobile.present? ?
      "#{I18n.t('user.address_for_business_card.mobile')} #{shop.address.mobile_number}\n" :
      '') +
    "#{I18n.t('user.address_for_business_card.email')} #{email}"
  end

  def use_or_generate_purchase
    last_purchase = purchases.last
    user_address = address.attributes.except('id')
    if last_purchase.nil? || last_purchase.confirmed?
      @purchase = purchases.create
    else
      @purchase = last_purchase
    end

    @articles = shopping_baskets.map(&:article)

    # remove removed articles_orders
    @purchase.articles_orders.each do |articles_order|
      if !@articles.include?(articles_order.original_article) ||
         !articles_order.original_article_not_changed?
        articles_order.delete_voucher_discount
        articles_order.destroy
      end
    end

    @articles.group_by(&:user_id).each do |user_id, articles|
      # Create an Order
      new_order = @purchase.orders.find_or_initialize_by(seller_id: user_id)
      new_order.seller_address = User.find(user_id).address.dup
      new_order.save!

      # Fill the Order with ArticlesOrders
      articles.each do |article|
        old_articles_order =
          new_order.articles_orders
                   .find_by(original_article_id: article.id)
        article_in_cart = article.shopping_baskets
                                 .find_by(user_id: id)
        if old_articles_order.present?
          articles_order = old_articles_order
        else
          articles_order = 
            new_order.articles_orders.new(
              original_article_id: article.id,
              article_id: article.create_ordered_article.id)
        end

        articles_order.message_text    = article_in_cart.message_text
        articles_order.message_sent_at = article_in_cart.message_sent_at
        articles_order.amount          = article_in_cart.article_amount

        if old_articles_order.present?
          articles_order.save!(validate: false)
        else
          articles_order.build_shipping_address user_address
          articles_order.build_payment_address user_address
          articles_order.save!(validate: false)
          if articles_order.shipping_address.all_filled?
            articles_order.use_shipping_address_for_payment_address = true
          end
        end
        unless articles_order.available_countries_except_forbidden
                             .include?(articles_order.shipping_address.country)
          articles_order.shipping_address.update_attribute('country', '')
        end
      end
      new_order.save!
    end

app/views/pictures/_crop.html.slim
.crop_picture
  .head
    .cancel.glyphicon.glyphicon-remove-sign
    h2 = t '.edit_picture'
  .container-for-preview
    = image_tag @picture.image_url + '?' + Time.now.strftime("%H%M%S"),
        class: 'crop_image'
        / 'image-width' => MiniMagick::Image.open(Picture.last.image.path)[:width],
        / 'image-height' => MiniMagick::Image.open(Picture.last.image.path)[:height]
  br
  .previews
    .large.preview
    .middle.preview
    .small.preview
    .extra-small.preview
  .right
    br
    .change_color data-opacity='.5'
    = t '.change_color'
    br
    br
    .btn.btn-default.rotate = t '.rotate'
    '
    .btn.btn-default.zoom-in
      .glyphicon.glyphicon-zoom-in
    '
    .btn.btn-default.zoom-out
      .glyphicon.glyphicon-zoom-out
    br
    br
    div
      = form_for @picture,
          url: crop_picture_url(@picture),
          remote: true,
          method: :post do |f|
        - for attribute in [:x, :y, :width, :height, :rotate]
          = f.hidden_field attribute, id: 'picture_' + attribute.to_s
        .btn.btn-default.cancel = t '.cancel'
        '
        = f.submit t('.save'), class: 'btn btn-default save', data: { disable_with: t('.save') }
  .clear

app/views/pictures/_form.html.slim
= form_for Image.new,
    url: pictures_path,
    html: { id: 'new_picture'},
    remote: true do |f|
  .field = f.file_field :image,
            id: 'picture_image'

app/views/pictures/_picture.html.slim
- if picture.image?
  = image_tag picture.image_url, class: "usual_picture"

app/views/pictures/_picture_edit.html.slim
.picture.inblock_top id='picture_#{picture.id}'
  = image_tag picture.image.small.url
  br
  = link_to picture_path(picture),
      method: :delete,
      remote: true
    .glyphicon.glyphicon-remove-sign title='#{t '.delete_picture'}'
  '
  = link_to edit_picture_url(picture),
      remote: true
    = image_tag 'pencil.jpg',
        title: t('.edit_picture'),
        class: 'edit_icon'
  = hidden_field_tag 'picture_ids[]', picture.id
  = check_box_tag 'article[main_picture_id]',
      picture.id,
      picture.main?

app/views/pictures/create.js.erb
<% if @picture.errors.count == 0 %>

  $('#pictures_place .loading').before("<%= j render partial: 'pictures/picture_edit', locals: { picture: @picture } %>");

  $('div#<%= dom_id(@picture) %>').effect('highlight');

  $("#shop-form .edit_picture").remove()

  // remove add-picture-button when the amount of the pictures more than 2
  if ($("#shop-form #pictures_place .picture").length == 2) {
    $('#add_picture').hide();
  };

  if ($(".shop_edit #pictures_place .picture").length == 2) {
    $('#add_picture').hide();
  };

  // remove add-picture-button when the amount of the pictures more than 10
  if ($("#article-form #pictures_place .picture").length == 10) {
    $('#add_picture').hide();
  };

  if ($("#article-form #pictures_place .picture").length == 1) {
  	$('.picture [type=checkbox]:first').prop('checked', true)
  };


<% else %>
  alert("<% @picture.errors.full_messages.each do |message| %><%= message.html_safe %>\n<% end %>");
<% end %>

$('#pictures_place .loading').hide();

$("#picture_image").change(function() {
    $("#pictures_place .loading").fadeIn()
    $("#new_picture").trigger('submit.rails')
});

if ($("#article-pictures [type=checkbox]").prop("checked") != true) {
  $("#article-pictures [type=checkbox]").first().click()
};

$('.about_me_shops_pictures, #shop-form #pictures_place').find('[type=checkbox]').remove()

app/views/pictures/crop.js.erb
$('.crop_picture').remove()
$('#main_picture_<%= @picture.id %> img:first').attr('src', '<%= @picture.image.url %>?' + (new Date().getTime()))  
$('#picture_<%= @picture.id %> img:first').attr('src', '<%= @picture.image.small.url %>?' + (new Date().getTime()))

app/views/pictures/destroy.js.erb
$('#picture_<%= @picture.id %>, #main_picture_<%= @picture.id %>').fadeOut();
$('#picture_<%= @picture.id %>, #main_picture_<%= @picture.id %>').remove();

<% unless @picture.shop_main_pictures? %>
$('#add_picture').show();
<% end %>

if ($('.picture [type=checkbox]:checked').length == 0){
  $('.picture [type=checkbox]:first').prop('checked', true)
};

if (!$('.main_picture_block .main_picture').length && $('.main_picture_block #add_main_picture_button').length) {
  $('.main_picture_block #add_main_picture_button').show()
  $("#main_picture_image").change(function(){
    $(this).closest('form').submit();
  })

  $("#main_picture_image").change(function(){
    $('#add_main_picture_button').hide();
    $('.main_picture_block .loading').fadeIn();
  });
}