config/routes.rb
WeltDerUnikate::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  constraints subdomain: 'www' do
    get ':any', to: redirect(subdomain: nil, path: '/%{any}'), any: /.*/
  end

  constraints subdomain: 'administration' do
    namespace(:admin, path: '/') do
      get '/' => :show
      get :maillog
      resources :art_associations, except: [:destroy, :show]
      resources :members do
        get :update_monthly_charge_for_all_users
        member do
          get :purchases_and_sales
          get :user_profile
          get :user_settings
          get "shop_profile/about_me"           => :shop_profile_about_me
          get "shop_profile/settings"           => :shop_profile_settings
          get "shop_profile/terms_and_imprint"  => :shop_profile_terms_and_imprint
          get "shop_profile/revocation"         => :shop_profile_revocation
          post :update_user_data
          get :update_monthly_charge_for_the_user
          get :restore_deleted_account
        end
      end
      resources :invoices, only: [] do
        collection do
          get :created
          get :open
          get :paid
          get :cancellations
          get :credits
          get :check_boxes_action
          get :send_monthly_invoice
          get :send_commission_invoice
        end
      end
      resources :correspondence, only: [:index] do
        collection do
          get :registration
          get :new_shop
          get :to_old_email_about_email_changing
          get :confirmation_email
          get :password_changed
          get :articles_order_dispatched
          get :article_is_already_sold
          get :new_order_message_from_buyer
          get :new_order_message_from_seller
          get :buyer_cancellation
          get :seller_cancellation
          get :new_message
          get :purchase_notification_confirmed_to_buyer
          get :purchase_notification_confirmed_to_seller
          get :purchase_notification_unconfirmed_to_buyer
          get :purchase_notification_unconfirmed_to_seller
          get :share_article
          get :new_voucher
        end
      end
      resources :newsletters, only: [:new, :create]
      resources :business_cards, only: [:index] do
        post :change_details, on: :member
      end
      resources :vouchers, only: :index do
        get :change, on: :collection
        member do
          post :change_status
          post :change_paid_on
        end
      end
      get :text_content
      scope :text_content do
        resources :faq_sections,
            param: :faq_section_id do
          member do
            resources :faq_questions,
                param: :faq_question_id,
                except: :index
          end
        end
        get :discover_the
        get :find_yours
      end
    end
  end

  get 'admin', to: redirect(subdomain: 'administration', path: '/')
  get 'admin/:any', to: redirect(subdomain: 'administration', path: '/%{any}')

  constraints subdomain: false do
    resources :invoices, only: [:index, :show]
  end
  resources :invoices, only: [] do
    get :pdf_version, on: :member
  end

  resources :favorites, only: [:index, :create, :destroy]
  resources :favorite_shops, only: [:index, :create, :destroy]
  resources :articles_view_types, only: [] do
    get :change, on: :collection
  end

  resources :messages, except: [:index] do
    member do
      get :reply
      get :to_trash
    end
    collection do
      get  :inbox
      get  :sent
      get  :drafts
      get  :bin
      get  :archive
      post :check_boxes_action
      get  :empty_trash
    end
  end

  resources :orders do
    collection do
      get :open
      get :completed
      get :canceled
    end
  end

  resources :purchases do
    member do 
      get  :addresses_and_payment_types
      get  :check_order
      get  :complete
    end
    collection do
      get :open
      get :completed
    end
  end

  resources :articles, except: :index do
    post :change, on: :member
    collection do
      get :sold
      get :deleted
      get :delete_all
      get :online
      get :offline
      get :templates
    end
  end


  resources :documents

  scope :search do
    get '/:search', to: 'articles#search'
    get '/', to: 'articles#search'
  end

  resources :payment_infos
  resources :payment_selections
  resources :shipping_methods
  resources :pictures, only: [:create, :destroy, :edit] do
    post :crop, on: :member
    post :create_shop_main, on: :collection
  end

  resources :withdrawal_forms, only: [:create, :destroy] do
    get :preview, on: :member
  end

  resources :shopping_baskets, only: [:create,
                                      :index,
                                      :update,
                                      :destroy]

  resources :articles_orders, only: [:destroy] do
    member do
      get :paypal_payment
      get :bank_details
      get :credit_card_payment
      post :credit_card_payment
      get :write_a_review
      get :write_a_review_for_buyer
      get :mark_as_sold
      get :mark_order_messages_as_read
      patch :use_voucher
      patch :set_payment_type
      patch :set_pickup_as_shipping_method
      patch :use_shipping_address
      get :closure_confirmation
      get :close
      get :cancel
      patch :update_status
      get :send_payment_reminder
    end
  end

  resources :credit_card_data, only: [:create]

  get '/' => 'shops#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != "www"}

  controller :pages do
    root to: :home
    get :imprint
    get :privacy
    get :about_jakira
    get :terms
  end

  resources :categories, only: :show

  devise_for :users, controllers: {registrations: 'users/registrations',
                                   sessions: 'users/sessions',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations',
                                   omniauth_callbacks: "users/omniauth_callbacks"}
  # devise_scope :user do
  #   get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #   get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  # end

  resources :ratings, only: [:update, :index]

  resources :shops, except: [:edit, :index] do
    collection do
      get :about_me
      get :settings
      get :terms_and_imprint
      get :revocation
      get :open
    end
    member do
      get :show_terms
      get :show_revocation
      get :ratings
      get :download_withdrawal_form
    end
  end

  resources :order_messages, only: [:create, :show]
  resources :share, only: [:new, :create, :index]

  resources :business_cards, only: [:index, :create]

  resources :vouchers, only: [:show, :new, :create] do
    get :after_payment, on: :collection
    get :pdf_version, on: :member
  end

  resources :main_voucher_data, only: :update

  resources :addresses, only: [] do
    get :load_country_code, on: :collection
    member do
      post :update_purchase_address
    end
  end

  resources :art_associations,
      only: [:create, :index] do
    collection do
      get :register
      patch :become_a_member
      scope :admin_panel, as: 'admin_panel' do
        get :events
        get :settings
        scope as: 'art_associations' do
          resources :members,
              controller: 'art_associations/members',
              except: [:show, :destroy] do
            post :import_xls, on: :collection
          end
        end
      end
    end
  end

  resources :faq, only: [:index, :show]

  get '/contact', to: 'contacts#new'
  resources :contacts, only: [:create]
end

app/models/article.rb
# Represents an article.
class Article < ActiveRecord::Base
  enum order_confirmation: [:automatically,
                            :manually,
                            :with_exception]
  enum status:       [:online, :offline, :sold]
  enum article_type: [:physical, :digital, :service]
  enum made_in_year: ["1299_and_older",
                      "1300 – 1399",
                      "1400 – 1499",
                      "1500 – 1599",
                      "1600 – 1699",
                      "1700 – 1799",
                      "1800 – 1899"] +
                        (1900..Time.now.year).to_a.map(&:to_s)
  enum textile_size: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "XXXXL", "one_size"]
  enum kind: [:normal, :template, :ordered]
  enum art_type: [:applied_art, :fine_art, :old_masters]

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  attr_accessor :save_as_template

  before_save :change_status_to_offline
  before_save :set_template_name, if: -> {kind == "template" && template_name.nil?}
  after_save :create_template, if: -> {save_as_template == '1'}
  after_save :check_if_pictures_have_images
  
  validates_presence_of :template_name,
    if: -> {save_as_template == '1'}
  validates :template_name,
    uniqueness: { scope: :user_id },
      if: -> {save_as_template == '1' && template_name.present?}

  validates_presence_of :categories,
                        :article_type,
                        :artist,
                        :materials,
                        :colors,
                        :suitable_fors,
                        :art_type

  validates_presence_of :payment_types

  validates :title, length: {minimum: 3, maximum: 255}
  validates :price_cents, numericality: {greater_than: 0}
  validates :description, length: {minimum: 5, maximum: 3000}

  belongs_to :user
  has_one :shop, through: :user

  has_and_belongs_to_many :categories
  has_and_belongs_to_many :materials
  has_and_belongs_to_many :payment_types
  has_and_belongs_to_many :colors
  has_and_belongs_to_many :gem_colors
  has_and_belongs_to_many :suitable_fors

  has_one :bank_transfer_data,
    as: :bank_transfer_datable,
    inverse_of: :bank_transfer_datable,
    dependent: :destroy

  has_one :paypal_data,
    as: :paypal_datable,
    inverse_of: :paypal_datable,
    dependent: :destroy

  has_one :shipping_readiness, inverse_of: :article

  belongs_to :main_picture,
             class_name: 'Image'

  has_many :pictures,
           -> { article_pictures },
           class_name: 'Image',
           foreign_key: :parent_id,
           inverse_of: :article

  has_many :material_textiles, inverse_of: :article

  has_many :shipping_methods, as: :shipping_methodable,
                              inverse_of: :shipping_methodable

  has_many :documents

  has_many :shopping_baskets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one :articles_order
  has_many :orders, through: :articles_orders

  monetize :price_cents

  accepts_nested_attributes_for :pictures,
                                :shipping_methods,
                                :material_textiles,
                                :shipping_readiness

  accepts_nested_attributes_for :bank_transfer_data, allow_destroy: true
  accepts_nested_attributes_for :paypal_data, allow_destroy: true

  scope :latest, -> { order('articles.created_at DESC') }

  scope :not_deleted, -> { where(deleted: false) }

  scope :deleted, -> { where(deleted: true)
                      .where(completely_deleted: nil)}

  scope :visible, -> { not_deleted
                      .normal
                      .where("articles.status = ? OR (articles.status = ? AND articles.sold_at > ?)",
                        Article.statuses[:online],
                        Article.statuses[:sold],
                        3.days.ago)
                      .joins(user: :shop)
                      .where(shops: {online: true})
                      .latest }

  scope :search, lambda { |text|
    if text
       includes(:categories)
      .includes(:user)
      .includes(:shop)
      .includes(:materials)
      .includes(:colors)
      .where('LOWER(articles.title) LIKE :search
           OR LOWER(articles.artist) LIKE :search
           OR LOWER(categories.name) LIKE :search
           OR LOWER(users.nickname) LIKE :search
           OR LOWER(shops.name) LIKE :search
           OR LOWER(materials.name) LIKE :search
           OR LOWER(colors.name) LIKE :search',
           search: "%#{text.downcase}%")
      .references(:categories)
      .references(:user)
      .references(:shop)
      .references(:materials)
      .references(:colors)
    else
      all
    end
  }

  scope :search_in_category, lambda { |text|
    if text
      where('LOWER(articles.title) LIKE ?', "%#{text.downcase}%")
    else
      all
    end
  }

  # This overrides the 'has_many :documents' association
  def documents
    Document.where(article_id: self.id).where(type: nil)
  end

  # If vat is true, VAT will be included in the calculation.
  def price_vat
    p = self.price
    if vat && self.vat != nil
      p + p * self.vat/100
    else
      p
    end
  end

  # Defines the last part of the SEO url of this resource.
  def slug_candidates
    if categories == nil
      [
        :title,
        [:title, :id]
      ]
    else
      [
        :title,
        [self.categories.name, :title],
        [:title, :id]
      ]
    end
  end

  def categories_with_backslashes
    Category.sort_by_ancestry(self.categories).map do |category|
      if category.ancestry == '1'
        ' / ' + category.name
      else
        '-' + category.name
      end
    end.join()[3..-1]
  end

  def main_picture_url
    if self.main_picture.present?
      self.main_picture.image_url
    else
      'placeholder.gif'
    end
  end

  def main_picture_for_mobile_url
    if self.main_picture.present?
      self.main_picture.image.for_mobile.url
    else
      'placeholder.gif'
    end
  end

  def small_main_picture
    if self.main_picture.present?
      self.main_picture.image.small.url
    else
      'placeholder.gif'
    end
  end

  def middle_main_picture
    if self.main_picture.present?
      self.main_picture.image.middle.url
    else
      'placeholder.gif'
    end
  end

  def textile_size_value
    I18n.t(textile_size, default: textile_size) if textile_size.present?
  end

  def no_shipping_to_the_following_countries
    if no_shipping_to_the_countries.present?
      countries = no_shipping_to_the_countries
      countries.delete("")
      array = countries.collect do |c|
        country = ISO3166::Country[c]
        country.translations[I18n.locale.to_s] || country.name if country.present?
      end
      array.join(', ')
    end
  end

  def create_ordered_article
    article = Article.new(attributes.except('id',
                                            'slug',
                                            'created_at',
                                            'updated_at'))
    article.kind          = "ordered"
    article.materials     = materials
    article.colors        = colors
    article.gem_colors    = gem_colors
    article.suitable_fors = suitable_fors
    article.categories    = categories
    article.payment_types = payment_types
    shipping_methods.each do |shipping_method|
      article.shipping_methods
             .build(shipping_method.attributes
                                   .except('id', 'shipping_methodable_id'))
    end
    article.save!
    pictures.each do |picture|
      created_picture = article.pictures.create(image: picture.image)
      article.main_picture_id = created_picture.id if picture.main?
      article.save!
    end
    material_textiles.each do |material_textile|
      article.material_textiles
             .create(material_textile.attributes
                                     .except('id', 'article_id'))
    end
    if paypal_data.present?
      article.create_paypal_data(paypal_data.attributes
                                            .except('id', 'paypal_datable_id'))
    end
    if bank_transfer_data.present?
      article.create_bank_transfer_data(bank_transfer_data.attributes
                                     .except('id', 'bank_transfer_datable_id'))
    end
    article.create_shipping_readiness(shipping_readiness.attributes
                                                        .except('id'))
    article
  end

  def self.years(custom_year=nil)
    array = ["1299_and_older", "1300 – 1399", "1400 – 1499",
             "1500 – 1599", "1600 – 1699", "1700 – 1799",
             "1800 – 1899"] + (1900..Time.now.year).to_a.map(&:to_s)
    array += [custom_year] if custom_year.present? && array.exclude?(custom_year)
    array
  end

  def available_countries
    shipping_methods_names = shipping_methods.collect(&:name)

    if shipping_methods_names.include?('worldwide')
      ISO3166::Country.all.map(&:alpha2)
    elsif shipping_methods_names.include?('within_eu')
      ISO3166::Country.all.select(&:in_eu?).map(&:alpha2)
    elsif shipping_methods_names.include?('free_within_germany') || 
          shipping_methods_names.include?('within_germany')
      ['DE']
    else
      []
    end
  end

   def available_countries_except_forbidden
    if no_shipping_to_the_countries.present?
      available_countries - no_shipping_to_the_countries
    else
      available_countries
    end
   end

  def self.material_textiles_names 
    %w(alcantara angora cotton_blended cotton_pure
       organic_fabric chiffon cord elastane fur
       felt fleece yarn rubber wood jeans jersey
       kashmir synthetic_fiber faux_fur
       faux_leather latex leather linen merino
       metal mixed_fabrics modal mohair organza
       plush polyester velvet satin sailcloth
       silk lace tarpaulin pleating taffeta
       tulle viscose oilcloth wool)
  end

  def self.gems
    %w(agate alexandrite amazonit amethyst ametrine apatite apophyllit

app/views/categories/_breadcrum.html.erb
<% for cat in category.ancestors %>
    <% unless cat.root? %>
        <%= link_to h(cat.name), cat %> &gt;
    <% else %>
        <%= link_to 'Jakira', controller: 'pages', action: 'home'  %> &gt;
    <% end %>
<% end %>

<% if defined? article %>
  <%= link_to h(category.name), category %> &gt; <span class="category-breadcrum-last"><%= article.title %></span>
<% else %>
    <span class="category-breadcrum-last"><%= category.name %></span>
<% end %>

app/views/categories/_filtered_articles.html.slim
- if @articles.empty?
  .no_articles = t '.no_articles_with_criteria'
- else
  - @articles.each do |article|
    = render partial: 'articles/categories_article_block',
        locals: {article: article}

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit, data: { disable_with: '' } %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Kategorieliste</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Überkategorie</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent.blank? ? '-' : category.parent.name %></td>
        <td><%= link_to 'Bearbeiten', edit_category_path(category) %></td>
        <td><%= link_to 'Löschen', category_path(category), method: :delete, data: { confirm: t('are_you_sure?') } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to t('back'), root_url(subdomain: "administration") %> | <%= link_to 'Neue Kategorie', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render '/admin/categories/form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.slim
- content_for :title, @category.name
#upper-path
  = image_tag 'arrow_to_left.png'
  = link_to 'Jakira', root_url
  span  &bull; 
  = link_to @main_category.name,
      @main_category,
      class: 'without-underline-if-mobile'
  - if @second_category.present?
    span  &bull; 
    = link_to @second_category.name,
        @second_category,
        class: 'without-underline-if-mobile'
  - if @third_category.present?
    span  &bull; 
    = link_to @third_category.name,
        @third_category,
        class: 'without-underline-if-mobile'

.category_page
  = cache "category_#{@main_category.id}"
    .left_menu
      .main.category = link_to @main_category.name,
                          category_url(@main_category)
      .mobile_subcategories.open_button
        = t('.subcategories')
        .arrow_to_right
          .back_triangle
          .front_triangle
        .arrow_to_down
          .back_triangle
          .front_triangle
      .subcategories_wrapper
        .mobile.filter
          = form_tag category_url(@category),
              method: :get,
              remote: true,
              onsubmit: '$("body").spin()'
            = text_field_tag :mobile_search_in_category,
                params[:mobile_search_in_category],
                placeholder: t('.search_', category: @category.name)
            = image_submit_tag 'search_button_icon.png',
                class: 'search_button_icon',
                data: { disable_with: '' }
        - @main_category.children.reorder(name: :asc).each do |c|
          .sub.category
            = link_to c.name, category_url(c)
          - c.children.reorder(name: :asc).each do |c|
            .subsub.category
              = link_to c.name, category_url(c)
          - if c.children.present?
            br
  .article-list-section
    .mobile_filters.open_button
      = t('.filter')
      .arrow_to_right
        .back_triangle
        .front_triangle
      .arrow_to_down
        .back_triangle
        .front_triangle
    .filters
      .filters_boxes
        .title = t '.filter_'
        .filter_box_prototype
          .close_filter X
          .key
          span.value
      = form_tag category_url(@category),
          method: :get,
          id: 'category_filters',
          remote: true,
          onsubmit: '$("body").spin()'
        .filter
          .hidden_fields
            = text_field_tag :min_price,
                params[:min_price],
                peak: @min_price_peak
            = text_field_tag :max_price,
                params[:max_price],
                peak: @max_price_peak
          .button
            = t '.price'
            .arrow-wrapper
              .arrow-down-white
              .arrow-down-gray
            .arrow_to_right
              .back_triangle
              .front_triangle
            .arrow_to_down
              .back_triangle
              .front_triangle
          .drop-down.price_range
            .price_container
              span.show_price_symbol &euro;
              span#show_min_price = @min_price
            .price_container
              span.show_price_symbol &euro;
              span#show_max_price = @max_price
            .clear
            .slider_block
              #price_filter_slider
            .apply = t('.apply')
        .filter
          .hidden_fields
            = select_tag :textile_sizes,
                options_for_select(@textile_sizes.collect { |k, v| [t(k, default: k), v]},
                params[:textile_sizes]),
                multiple: true,
                prompt: t('.size')
          .button
            = t '.size'
            .arrow-wrapper
              .arrow-down-white
              .arrow-down-gray
            .arrow_to_right
              .back_triangle
              .front_triangle
            .arrow_to_down
              .back_triangle
              .front_triangle
          .drop-down.list.regular
            - @textile_sizes.each do |k, v|
              .element value="#{v}" = t(k, default: k)
        .filter
          .hidden_fields
            = select_tag :color_ids,
                options_for_select(@colors.collect { |color| [color.name.capitalize,
                      color.id]},
                params[:color_ids]),
                multiple: true,
                prompt: t('.color')
          .button
            = t '.color'
            .arrow-wrapper
              .arrow-down-white
              .arrow-down-gray
            .arrow_to_right
              .back_triangle
              .front_triangle
            .arrow_to_down
              .back_triangle
              .front_triangle
          .drop-down.list.colors_filter
            - @colors.each do |color|
              .element value="#{color.id}" title="#{color.name.capitalize}"
                - Globalize.with_locale(:en)
                  .color style='background-color:#{color.name.delete(" ")}'
                    - if color.name == 'colorful'
                      .triangle.first.top
                      .triangle.secont.top
                      .triangle.third.top
                      .triangle.fourth.top
                      .triangle.first.bottom
                      .triangle.secont.bottom
                      .triangle.third.bottom
                      .triangle.fourth.bottom
        - if @motives.present?
          .filter
            .hidden_fields
              = select_tag :motive,
                  options_for_select(@motives,
                  params[:motive]),
                  multiple: true,
                  prompt: t('.motive')
            .button
              = t '.motive'
              .arrow-wrapper
                .arrow-down-white
                .arrow-down-gray
              .arrow_to_right
                .back_triangle
                .front_triangle
              .arrow_to_down
                .back_triangle
                .front_triangle
            .drop-down.list.regular
              - @motives.each do |motive|
                .element value="#{motive}" = motive
        - if @artists.present?
          .filter
            .hidden_fields
              = select_tag :artist,
                  options_for_select(@artists,
                  params[:artist]),
                  multiple: true,
                  prompt: t('.artist')
            .button
              = t '.artist'
              .arrow-wrapper
                .arrow-down-white
                .arrow-down-gray
              .arrow_to_right
                .back_triangle
                .front_triangle
              .arrow_to_down
                .back_triangle
                .front_triangle
            .drop-down.list.regular
              - @artists.each do |artist|
                .element value="#{artist}" = artist
        .filter.right
          = text_field_tag :search_in_category,
              params[:search_in_category],
              placeholder: t('.search')
          = image_submit_tag 'search_button_icon.png',
              class: 'search_button_icon',
              data: { disable_with: '' }
    .clear
    .filtered_articles
      = render 'categories/filtered_articles'

app/views/categories/show.js.erb
history.pushState('', '', '<%= request.base_url + request.original_fullpath %>')
$(".filtered_articles").html("<%= j render partial: 'categories/filtered_articles' %>")
$('.spinner').remove()